export const testConfig = {
    qa: `https://qaportal.catchpoint.com/ui/`,
    stage: `https://portalstage.catchpoint.com/ui/Symphony/`,
    production: `https://portal.catchpoint.com/ui/Symphony/`,
    portala: `https://portala.catchpoint.com/ui/Symphony/`,
    portalb: `https://portalb.catchpoint.com/ui/Symphony/`,
    portalc: `https://portalc.catchpoint.com/ui/Symphony/`,
    cpun:`qaautomationxclient-clientadministrator@catchpoint.com`,
    cppwd : `Password123!`,
    produn: `EngUI@catchpoint.com`,
    prodpwd:`Password123!`,
    waitTimeForElement : 5000,
    waitTimeForPageLoad : 20000,
    password: 'Test',
}